// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-fastly/blob/master/website/docs/r/service_dictionary_items_v1.html.markdown.
 */
export class ServiceDictionaryItmesv1 extends pulumi.CustomResource {
    /**
     * Get an existing ServiceDictionaryItmesv1 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceDictionaryItmesv1State, opts?: pulumi.CustomResourceOptions): ServiceDictionaryItmesv1 {
        return new ServiceDictionaryItmesv1(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fastly:index/serviceDictionaryItmesv1:ServiceDictionaryItmesv1';

    /**
     * Returns true if the given object is an instance of ServiceDictionaryItmesv1.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceDictionaryItmesv1 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceDictionaryItmesv1.__pulumiType;
    }

    /**
     * The ID of the dictionary that the items belong to
     */
    public readonly dictionaryId!: pulumi.Output<string>;
    /**
     * A map representing an entry in the dictionary, (key/value)
     */
    public readonly items!: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * The ID of the service that the dictionary belongs to
     */
    public readonly serviceId!: pulumi.Output<string>;

    /**
     * Create a ServiceDictionaryItmesv1 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceDictionaryItmesv1Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceDictionaryItmesv1Args | ServiceDictionaryItmesv1State, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as ServiceDictionaryItmesv1State | undefined;
            inputs["dictionaryId"] = state ? state.dictionaryId : undefined;
            inputs["items"] = state ? state.items : undefined;
            inputs["serviceId"] = state ? state.serviceId : undefined;
        } else {
            const args = argsOrState as ServiceDictionaryItmesv1Args | undefined;
            if (!args || args.dictionaryId === undefined) {
                throw new Error("Missing required property 'dictionaryId'");
            }
            if (!args || args.serviceId === undefined) {
                throw new Error("Missing required property 'serviceId'");
            }
            inputs["dictionaryId"] = args ? args.dictionaryId : undefined;
            inputs["items"] = args ? args.items : undefined;
            inputs["serviceId"] = args ? args.serviceId : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(ServiceDictionaryItmesv1.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceDictionaryItmesv1 resources.
 */
export interface ServiceDictionaryItmesv1State {
    /**
     * The ID of the dictionary that the items belong to
     */
    readonly dictionaryId?: pulumi.Input<string>;
    /**
     * A map representing an entry in the dictionary, (key/value)
     */
    readonly items?: pulumi.Input<{[key: string]: any}>;
    /**
     * The ID of the service that the dictionary belongs to
     */
    readonly serviceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ServiceDictionaryItmesv1 resource.
 */
export interface ServiceDictionaryItmesv1Args {
    /**
     * The ID of the dictionary that the items belong to
     */
    readonly dictionaryId: pulumi.Input<string>;
    /**
     * A map representing an entry in the dictionary, (key/value)
     */
    readonly items?: pulumi.Input<{[key: string]: any}>;
    /**
     * The ID of the service that the dictionary belongs to
     */
    readonly serviceId: pulumi.Input<string>;
}
